In [6]:
import pandas as pd

In [7]:
cafe_data = pd.read_csv("data/cafes-and-restaurants-with-seating-capacity.csv")
cafe_data

,census_year,block_id,property_id,base_property_id,building_address,clue_small_area,trading_name,business_address,industry_anzsic4_code,industry_anzsic4_description,seating_type,number_of_seats,longitude,latitude,location
0,2007,13,110151,110151,22-38 William Street MELBOURNE 3000,Melbourne (CBD),Cafe 22,"Part Ground , 22 William Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Indoor,75,144.959975,-37.818778,"-37.8187779, 144.959974759"
1,2007,14,103166,103166,7-9 Elizabeth Street MELBOURNE 3000,Melbourne (CBD),Pepperoni's,7A Elizabeth Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Indoor,70,144.964560,-37.817933,"-37.81793319, 144.964559723"
2,2007,14,103167,103167,11-15 Elizabeth Street MELBOURNE 3000,Melbourne (CBD),McDonald's,11-15 Elizabeth Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Outdoor,12,144.964509,-37.817831,"-37.81783056, 144.964509018"
3,2007,14,104004,104004,342-348 Flinders Street MELBOURNE 3000,Melbourne (CBD),Aria Cafe,"Part Ground , 342-348 Flinders Street MELBOURN...",4511,Cafes and Restaurants,Seats - Indoor,30,144.963086,-37.818453,"-37.81845283, 144.963085709"
4,2007,14,104008,104008,292-298 Flinders Street MELBOURNE 3000,Melbourne (CBD),Vita Juice Energy For Life,298 Flinders Street MELBOURNE 3000,4512,Takeaway Food Services,Seats - Indoor,11,144.964363,-37.818076,"-37.81807623, 144.964363152"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66351,2007,12,103999,103999,1-13 William Street MELBOURNE 3000,Melbourne (CBD),Williams Bar Cafe,"Restaurant , 1 William Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Outdoor,16,144.959520,-37.819434,"-37.81943422, 144.959520032"
66352,2007,12,105402,105402,8-10 King Street MELBOURNE 3000,Melbourne (CBD),Monkey Bar Noodles & Sushi,10 King Street MELBOURNE 3000,4511,Cafes and Restaurants,Seats - Indoor,30,144.957647,-37.819929,"-37.81992899, 144.957647321"
66353,2007,12,110091,110091,15-33 William Street MELBOURNE 3000,Melbourne (CBD),Hotel Food Drink,"Part Ground 0, 15-33 William Street MELBOURNE ...",4511,Cafes and Restaurants,Seats - Indoor,130,144.959197,-37.819217,"-37.81921707, 144.959197028"
66354,2007,13,104002,104002,376-388 Flinders Street MELBOURNE 3000,Melbourne (CBD),Gosh Cafe,"Shop 1, Ground , 376 Flinders Street MELBOURNE...",4512,Takeaway Food Services,Seats - Indoor,30,144.961539,-37.818848,"-37.81884761, 144.961539387"
66355,2007,13,106438,106438,14-40 Market Street MELBOURNE 3000,Melbourne (CBD),Koury's Coffee Lounge,"Part Ground , 389 Market Street MELBOURNE 3000",4511,Cafes and Restaurants,Seats - Indoor,43,144.961143,-37.818489,"-37.81848932, 144.96114339"

In [8]:
cafe_data = cafe_data[cafe_data["industry_anzsic4_description"] == "Cafes and Restaurants"]
cafe_data = cafe_data[["census_year","trading_name","business_address"]].drop_duplicates()
cafe_data

,census_year,trading_name,business_address
0,2007,Cafe 22,"Part Ground , 22 William Street MELBOURNE 3000"
1,2007,Pepperoni's,7A Elizabeth Street MELBOURNE 3000
2,2007,McDonald's,11-15 Elizabeth Street MELBOURNE 3000
3,2007,Aria Cafe,"Part Ground , 342-348 Flinders Street MELBOURN..."
5,2007,Kimchi Tray,294 Flinders Street MELBOURNE 3000
...,...,...,...
66342,2007,Time Out Cafe,"Tenancy 30, 2 Swanston Street MELBOURNE 3000"
66347,2007,Gurkha's Express,"Shop 1, 500 Flinders Street MELBOURNE 3000"
66348,2007,Florin Deli,490 Flinders Street MELBOURNE 3000
66352,2007,Monkey Bar Noodles & Sushi,10 King Street MELBOURNE 3000
66353,2007,Hotel Food Drink,"Part Ground 0, 15-33 William Street MELBOURNE ..."

In [15]:
cafes_by_year = cafe_data.groupby("census_year")['trading_name'].count()
cafes_by_year = cafes_by_year.rename("Number of Cafes")
cafes_by_year

census_year
2002     886
2003     914
2004     944
2005    1025
2006    1065
2007    1111
2008    1169
2009    1253
2010    1301
2011    1363
2012    1428
2013    1539
2014    1620
2015    1663
2016    1725
2017    1738
2018    1756
2019    1771
2020    1649
2021    1595
2022    1536
2023    1561
2024    1645
Name: Number of Cafes, dtype: int64

In [16]:
cafes_by_year.to_csv("data/cafes_by_year.csv")