In [59]:
import pandas as pd

In [60]:
trips = pd.read_csv("data/vista_trips_2023-2025.csv")
trips = trips[["year","origlga","destplace1","destplace2","destpurp1","destpurp2","destlga","triptime","cumdist"]]
trips = trips[(trips["year"] >= 2022) & (trips["destplace2"] == "Restaurant or Cafe") & (trips["destpurp2"] == "Ate or drank") & (trips["origlga"].str.endswith(" (C)"))]
trips = trips[~trips["origlga"].isin(["Warrnambool (C)", "Ballarat (C)", "Greater Geelong (C)", "Greater Bendigo (C)", "Greater Shepparton (C)"])]

trips["cumdist"] = pd.to_numeric(trips["cumdist"], errors="coerce")
trips["triptime"] = pd.to_numeric(trips["triptime"], errors="coerce")

trips["origlga"] = trips["origlga"].str.replace(" (C)", "", regex=False).str.upper()
trips

C:\Users\Ryan\AppData\Local\Temp\ipykernel_13084\2923573776.py:1: DtypeWarning: Columns (0: triptime, 1: travtime, 2: time1) have mixed types. Specify dtype option on import or set low_memory=False.
  trips = pd.read_csv("data/vista_trips_2023-2025.csv")

,year,origlga,destplace1,destplace2,destpurp1,destpurp2,destlga,triptime,cumdist
4,2024,GREATER DANDENONG,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Greater Dandenong (C),10,5.06795
63,2024,GREATER DANDENONG,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Greater Dandenong (C),3,1.12386
297,2024,YARRA,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Nillumbik (S),25,24.18257
302,2024,WHITTLESEA,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Whittlesea (C),2,0.55836
314,2024,WHITTLESEA,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Whittlesea (C),2,0.55836
...,...,...,...,...,...,...,...,...,...
70691,2022,KNOX,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Knox (C),3,1.78371
70755,2022,KNOX,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Knox (C),10,1.79484
70763,2022,KNOX,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Knox (C),2,0.05062
70977,2022,BOROONDARA,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Melbourne (C),50,13.89169
71017,2022,BOROONDARA,Entertainment venue,Restaurant or Cafe,Social,Ate or drank,Boroondara (C),5,0.36603

In [61]:
cafe_trips = trips[["origlga","triptime","cumdist"]].groupby("origlga").mean()
cafe_trips = cafe_trips.sort_values("cumdist").reset_index()
cafe_trips.to_csv("data/cafe_trips_by_lga.csv", index=False)
cafe_trips

              origlga   triptime    cumdist
0               YARRA  11.222222   2.298213
1           MELBOURNE  14.836364   2.639538
2          MANNINGHAM  13.584906   4.072022
3       MOONEE VALLEY  16.884615   4.082673
4         STONNINGTON  13.763636   4.280057
5          BOROONDARA  16.961039   4.845324
6        PORT PHILLIP  14.807018   5.003441
7            BRIMBANK  14.000000   5.398371
8           FRANKSTON  10.342857   5.467368
9             BANYULE  18.480769   6.143856
10            DAREBIN  18.375000   6.429556
11  GREATER DANDENONG  13.178571   6.435045
12        HOBSONS BAY  16.794872   6.908007
13             MONASH  16.764706   7.140221
14         WHITEHORSE  15.253521   7.230880
15               KNOX  13.590164   7.282852
16        MARIBYRNONG  16.928571   7.451928
17          MERRI-BEK  18.313433   7.535249
18          GLEN EIRA  18.277778   7.690508
19           KINGSTON  17.235294   8.332665
20          MAROONDAH  15.050000   9.977709
21            BAYSIDE  21.596774  10.010844
22               HUME  16.058824  12.713386
23         WHITTLESEA  23.523810  14.083546
24            WYNDHAM  27.925000  15.510706
25              CASEY  31.675000  22.286455