In [36]:
import pandas as pd

In [37]:
df2025 = pd.read_csv("data/trips_vista_2024_2025.csv")
df2024 = pd.read_csv("data/trips_vista_2023_2024.csv")
df2023 = pd.read_csv("data/trips_vista_2022_2023.csv")
# df2012to2020 = pd.read_csv("data/trips_vista_2012_2020_lga_v1.csv")

C:\Users\Ryan\AppData\Local\Temp\ipykernel_8432\3126875926.py:2: DtypeWarning: Columns (0: triptime, 1: travtime, 2: time1) have mixed types. Specify dtype option on import or set low_memory=False.
  df2024 = pd.read_csv("data/trips_vista_2023_2024.csv")

In [38]:
df2025['year'] = 2024
df2024['year'] = 2023
df2023['year'] = 2022
# Get the year from the 2 and 3 digit of persid, and add "20" in front of it to get the full year
# df2012to2020['year'] = "20" + df2012to2020['persid'].str.slice(1,3)

In [39]:
df = pd.concat([df2025, df2024, df2023], ignore_index=True)
df.to_csv("data/vista_trips_2023-2025.csv", index=False)
df.head()

,tripid,hhid,persid,tripno,starthour,startime,arrhour,arrtime,origplace1,origplace2,...,trippoststratweight_GROUP_5,trippoststratweight_GROUP_6,trippoststratweight_GROUP_7,trippoststratweight_GROUP_8,trippoststratweight_GROUP_9,trippoststratweight_GROUP_10,homesubregion_ASGS,homeregion_ASGS,dayType,year
0,Y25H6260101P01T01,Y25H6260101,Y25H6260101P01,1,7,456,8,512,Accommodation,Survey Home,...,1813.786567,2293.255058,2189.491855,2014.405624,1892.706790,0.0,MELB - Middle,Greater Melbourne,Weekday,2024
1,Y25H6260101P01T02,Y25H6260101,Y25H6260101P01,2,17,1020,18,1100,Place of work,My Workplace,...,1813.786567,2293.255058,2189.491855,2014.405624,1892.706790,0.0,MELB - Middle,Greater Melbourne,Weekday,2024
2,Y25H6260101P01T03,Y25H6260101,Y25H6260101P01,3,18,1115,18,1124,Retail venue,Supermarket,...,1813.786567,2293.255058,2189.491855,2014.405624,1892.706790,0.0,MELB - Middle,Greater Melbourne,Weekday,2024
3,Y25H6260101P01T04,Y25H6260101,Y25H6260101P01,4,18,1125,18,1128,Accommodation,Someone Elses Home,...,1813.786567,2293.255058,2189.491855,2014.405624,1892.706790,0.0,MELB - Middle,Greater Melbourne,Weekday,2024
4,Y25H6260102P01T01,Y25H6260102,Y25H6260102P01,1,10,630,10,640,Accommodation,Survey Home,...,1414.151169,1630.565161,1890.841711,1420.886488,1426.773563,0.0,MELB - Middle,Greater Melbourne,Weekday,2024

In [ ]:
# df2012to2020.columns = df2012to2020.columns.str.lower()
# shared_columns = list(set(df.columns).intersection(set(df2012to2020.columns)))
# df2012to2020 = df2012to2020[shared_columns]
# df = df[shared_columns]

In [ ]:
# df_combined = pd.concat([df, df2012to2020], ignore_index=True)
# df_combined = df_combined[~df_combined["linkmode"].isin(["Other","Plane"])]
# df_combined.to_csv("data/vista_trips_2012-2025.csv", index=False)
# df_combined.head()

,dist6,time9,time6,origpurp1,arrhour,dist2,origplace1,origplace2,dist9,origpurp2,...,destpurp1,hhid,trippurp,mode7,dist5,mode8,linkmode,tripno,time4,dist4
0,Not applicable,Not applicable,Not applicable,At Home,8,28.76045,Accommodation,Survey Home,Not applicable,Go home,...,Work Related,Y25H6260101,Work Related,Not applicable,Not applicable,Not applicable,Train,1,Not applicable,Not applicable
1,Not applicable,Not applicable,Not applicable,Work Related,18,28.76045,Place of work,My Workplace,Not applicable,Own Workplace,...,Buy Something,Y25H6260101,Buy Something,Not applicable,Not applicable,Not applicable,Train,2,Not applicable,Not applicable
2,Not applicable,Not applicable,Not applicable,Buy Something,18,Not applicable,Retail venue,Supermarket,Not applicable,Bought something,...,Other Purpose,Y25H6260101,Other Purpose,Not applicable,Not applicable,Not applicable,Vehicle Driver,3,Not applicable,Not applicable
3,Not applicable,Not applicable,Not applicable,Other Purpose,18,Not applicable,Accommodation,Someone Elses Home,Not applicable,Other (NEC),...,At Home,Y25H6260101,Other Purpose,Not applicable,Not applicable,Not applicable,Vehicle Driver,4,Not applicable,Not applicable
4,Not applicable,Not applicable,Not applicable,At Home,10,Not applicable,Accommodation,Survey Home,Not applicable,Go home,...,Social,Y25H6260102,Social,Not applicable,Not applicable,Not applicable,Vehicle Driver,1,Not applicable,Not applicable